business_related_words = [
    "quality", "size", "fit", "color", "style",
    "shipping", "delivery", "packaging", "customer service", "returns", "refunds", "exchange", "communication",
    "price", "cost", "affordable", "expensive", "worth", "value", "bargain",
    "user-friendly", "navigation", "website", "checkout", "search", "ease of use",
    "sale", "discount", "offer", "deal", "promo code",
    "fast", "slow", "tracking", "package", "condition", "timely",
    "brand names", "competitor names", "comparisons",
    "problem", "issue", "trouble", "difficulty",
    "how used", "application", "scenario",
    "payment", "checkout", "transaction", "payment process",
    "communication", "response time",
    "return", "exchange",
    "would recommend", "highly recommend", "unboxing", "packaging quality",
]
